export const allArticles = [
  // Emergency Care
  {
    title: "How to Identify Stroke Symptoms",
    summary: "Quick action can save lives. Learn the early signs of a stroke and how to respond immediately.",
    image: "/articles/stroke.jpg",
    link: "#",
    category: "Emergency Care",
  },
  {
    title: "Handling Heart Attacks at Home",
    summary: "Recognize symptoms and take immediate steps to help a loved one suffering a heart attack.",
    image: "/articles/heartattack.jpg",
    link: "#",
    category: "Emergency Care",
  },
  {
    title: "Burn Injuries: First Response Guide",
    summary: "Treat burns effectively before professional help arrives to reduce damage and pain.",
    image: "/articles/burns.jpg",
    link: "#",
    category: "Emergency Care",
  },
  {
    title: "CPR Basics Everyone Should Know",
    summary: "Learn the steps of CPR to save lives during cardiac emergencies.",
    image: "/articles/cpr.jpg",
    link: "#",
    category: "Emergency Care",
  },
  {
    title: "Managing Choking Emergencies",
    summary: "Effective techniques to assist someone who is choking and prevent suffocation.",
    image: "/articles/choking.jpg",
    link: "#",
    category: "Emergency Care",
  },
  {
    title: "Emergency Preparedness at Home",
    summary: "Create a safety plan and kit for medical emergencies at home.",
    image: "/articles/emergencykit.jpg",
    link: "#",
    category: "Emergency Care",
  },

  // Wellness
  {
    title: "Hydration and Health: What You Need to Know",
    summary: "Water is essential for life. Learn how much you really need and hydration tips.",
    image: "/articles/water.jpg",
    link: "#",
    category: "Wellness",
  },
  {
    title: "Benefits of Daily Meditation",
    summary: "Discover how meditation can improve mental clarity and reduce stress.",
    image: "/articles/meditation.jpg",
    link: "#",
    category: "Wellness",
  },
  {
    title: "Simple Exercises for Busy People",
    summary: "Short, effective workouts to keep you fit even with a busy schedule.",
    image: "/articles/exercise.jpg",
    link: "#",
    category: "Wellness",
  },
  {
    title: "Sleep Hygiene Tips",
    summary: "Improve your sleep quality with practical and easy-to-follow tips.",
    image: "/articles/sleep.jpg",
    link: "#",
    category: "Wellness",
  },
  {
    title: "Balanced Diet for a Healthy Life",
    summary: "Learn how to build a balanced meal plan for sustained wellness.",
    image: "/articles/diet.jpg",
    link: "#",
    category: "Wellness",
  },
  {
    title: "Managing Stress Naturally",
    summary: "Techniques and lifestyle changes to reduce stress without medication.",
    image: "/articles/stress.jpg",
    link: "#",
    category: "Wellness",
  },

  // Nutrition
  {
    title: "Safe Food Storage Tips",
    summary: "Prevent foodborne illness with these simple storage and handling practices.",
    image: "/articles/storage.jpg",
    link: "#",
    category: "Nutrition",
  },
  {
    title: "Affordable Nutrition for Families",
    summary: "Healthy eating on a budget: smart shopping and meal planning tips.",
    image: "/articles/affordable-nutrition.jpg",
    link: "#",
    category: "Nutrition",
  },
  {
    title: "Vitamins and Minerals Explained",
    summary: "Essential nutrients your body needs and how to get them naturally.",
    image: "/articles/vitamins.jpg",
    link: "#",
    category: "Nutrition",
  },
  {
    title: "Meal Prep Ideas for Busy Days",
    summary: "Prepare nutritious meals ahead of time to save effort and eat healthily.",
    image: "/articles/mealprep.jpg",
    link: "#",
    category: "Nutrition",
  },
  {
    title: "Understanding Food Labels",
    summary: "How to read and interpret nutritional information on packaged foods.",
    image: "/articles/foodlabels.jpg",
    link: "#",
    category: "Nutrition",
  },
  {
    title: "Hydrating Foods and Drinks",
    summary: "Beyond water: foods and beverages that keep you hydrated.",
    image: "/articles/hydrating-foods.jpg",
    link: "#",
    category: "Nutrition",
  },

  // Mental Health
  {
    title: "Mental Health After Crisis",
    summary: "How to support yourself and others emotionally after emergencies.",
    image: "/articles/mental.jpg",
    link: "#",
    category: "Mental Health",
  },
  {
    title: "Recognizing Anxiety Symptoms",
    summary: "Identify common signs of anxiety and strategies to manage it.",
    image: "/articles/anxiety.jpg",
    link: "#",
    category: "Mental Health",
  },
  {
    title: "Building Resilience",
    summary: "Techniques to strengthen your mental and emotional resilience.",
    image: "/articles/resilience.jpg",
    link: "#",
    category: "Mental Health",
  },
  {
    title: "Dealing with Depression",
    summary: "Ways to cope with depression and when to seek professional help.",
    image: "/articles/depression.jpg",
    link: "#",
    category: "Mental Health",
  },
  {
    title: "Mindfulness Practices",
    summary: "Simple mindfulness exercises to improve your mental well-being.",
    image: "/articles/mindfulness.jpg",
    link: "#",
    category: "Mental Health",
  },
  {
    title: "Stress Management Tips",
    summary: "Daily habits to reduce stress and improve your mental health.",
    image: "/articles/stress-management.jpg",
    link: "#",
    category: "Mental Health",
  },

  // First Aid
  {
    title: "Basic First Aid You Should Know",
    summary: "Learn the ABCs of first response to protect lives before help arrives.",
    image: "/articles/firstaid.jpg",
    link: "#",
    category: "First Aid",
  },
  {
    title: "Treating Minor Cuts and Scrapes",
    summary: "Clean and care for small wounds to prevent infection.",
    image: "/articles/cuts.jpg",
    link: "#",
    category: "First Aid",
  },
  {
    title: "Dealing with Sprains and Strains",
    summary: "How to manage common injuries with R.I.C.E. method.",
    image: "/articles/sprain.jpg",
    link: "#",
    category: "First Aid",
  },
  {
    title: "Recognizing Signs of Shock",
    summary: "What to look for and how to assist someone in shock.",
    image: "/articles/shock.jpg",
    link: "#",
    category: "First Aid",
  },
  {
    title: "Using an AED (Defibrillator)",
    summary: "A guide to safely operating an automated external defibrillator.",
    image: "/articles/aed.jpg",
    link: "#",
    category: "First Aid",
  },
  {
    title: "Choking First Aid",
    summary: "Step-by-step guide to help someone who is choking.",
    image: "/articles/choking.jpg",
    link: "#",
    category: "First Aid",
  },

  // Chronic Illness
  {
    title: "Managing Chronic Illness Daily",
    summary: "Tips for managing diabetes, asthma, and more to live well.",
    image: "/articles/chronic.jpg",
    link: "#",
    category: "Chronic Illness",
  },
  {
    title: "Understanding Diabetes",
    summary: "Basics of diabetes types, symptoms, and management.",
    image: "/articles/diabetes.jpg",
    link: "#",
    category: "Chronic Illness",
  },
  {
    title: "Living with Asthma",
    summary: "How to control asthma and reduce attacks effectively.",
    image: "/articles/asthma.jpg",
    link: "#",
    category: "Chronic Illness",
  },
  {
    title: "Heart Disease Prevention",
    summary: "Lifestyle changes to lower risk of heart disease.",
    image: "/articles/heart-disease.jpg",
    link: "#",
    category: "Chronic Illness",
  },
  {
    title: "Chronic Pain Management",
    summary: "Strategies to cope with and reduce chronic pain.",
    image: "/articles/chronic-pain.jpg",
    link: "#",
    category: "Chronic Illness",
  },
  {
    title: "Nutrition Tips for Chronic Illness",
    summary: "Diet recommendations to support chronic illness management.",
    image: "/articles/chronic-nutrition.jpg",
    link: "#",
    category: "Chronic Illness",
  },
];
