import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/css/globals.css'
import Navbar from "./Navbar";
import ContextProvider from "@/contextApi/ContextProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: "Cura Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body cz-shortcut-listen="true">
        <ContextProvider>
          <Navbar />
          {children}
          <ToastContainer position="top-center" />
        </ContextProvider>
      </body>
    </html>
  );
}
