import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/css/globals.css'
import ContextProvider from "@/contextApi/ContextProvider";
import { ToastContainer } from 'react-toastify';
import Nav from './Nav'
import 'react-toastify/dist/ReactToastify.css';
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Cura Link",
    description: "Generated by create next app",
};

export default function AppointmentLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                cz-shortcut-listen="true"
                className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
            >
                <ContextProvider>
                    <div className="min-h-screen bg-[#0E1724] text-white">
                        <div className="flex">
                            {/* Sidebar */}
                            <div className="w-56 bg-[#111926]">
                                <Nav />
                            </div>

                            {/* Main content */}
                            <div className="flex-1 p-6">
                                {children}
                            </div>
                        </div>
                    </div>

                    <ToastContainer position="top-center" />
                </ContextProvider>
            </body>
        </html>
    );
}

